apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hello-world
  name: hello-world
spec:
  containers:
    - name: hello-world
      image: ark3/hello-world
      ports:
        - containerPort: 8000
